// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
// RxJS
import 'rxjs';
//vendor libs
import 'three/examples/js/loaders/OBJLoader'
import 'moment/moment'